### ISSUE TITLE
[i3] Ly breaks urxvt

### ISSUE THREAD

**Issue by Jekuma** [cylgom/ly#100]
For some reason, whenever I have Ly enabled, it always breaks the configuration I had for urxvt in the .Xresources file. Any way to fix this?

**Comment by Kikubaaqudgha** [comment]
Maybe [this](https://github.com/cylgom/ly/issues/91) will help you.

**Comment by cylgom** [comment]
Anything new @Jekuma?

**Comment by nath1as** [comment]
Same issue, I have zsh, athame and urxvt.
@kikubaaqudgha 's solution brings color settings to urxvt, but the readline of athame doesn't work and the fonts and glyphs used by urxvt no longer work.

**Comment by gjorando** [comment]
[Fixed](https://github.com/cylgom/ly/commit/4c17b2f91d7beff4c0f8085ae7820978b26ec6f6).
