### ISSUE TITLE
linux-pam

### ISSUE THREAD

**Issue by Brutus11111** [cylgom/ly#101]
Hi,

I'm a bit confused. Which package am I supposed to use for linux-pam? I'm using MX Linux which is Debian based. 

I got installed:
```
libpam-gnome-keyring
libpam-modules
libpam-modules-bin
libpam-runtime
libpam0g
libpam-cgfs
libpam-cgfs-dbgsym
```

There is no package available called linux-pam.

This is where I'm stuck:

```
building source object obj/src/config.o
src/config.c:8:31: fatal error: security/pam_appl.h: No such file or directory
 #include <security/pam_appl.h>

compilation terminated.
makefile:39: recipe for target 'obj/src/config.o' failed
make: *** [obj/src/config.o] Error 1
```

I did find a website for linux-pam which leads to a github page that has broken software. I cloned the github repo and it tells me:
 ```-bash: .configure: command not found```.

**Comment by cylgom** [comment]
Hi, on debian-based distros it should be `libpam0g-dev`. Maybe the headers are misplaced, so if it stil doesn't work you can run `cd / && sudo find . -name "pam_appl.h"` and if it's not in the `security` folder, just create it where the file is and symlink it (or edit the source code)

**Comment by Brutus11111** [comment]
After installing `libpam0g-dev`, `Ly` successfully installed. I'm able to run the `Ly` application itself directly from a terminal emulator. I don't have `systemd`, so I thought I'd change the `/etc/X11/default-display-manager` to look at `/usr/bin/ly` but that breaks `xorg`.

**Comment by Brutus11111** [comment]
Little bit more information: I do have `systemd-logind`, but `sysvinit` is enabled by default. dmesg gives me the following error:

`Failed to start user service, ignoring: Unknown unit: user@1000.service`

After logging in to the TTY terminal, I can start ly and it shows me the display manager.

**Comment by ivanhercaz** [comment]
I just tried to install Ly in Debian but I got this error:
```
building source object obj/src/config.o
src/config.c:8:31: fatal error: security/pam_appl.h: No such file or directory
 #include <security/pam_appl.h>
```

But installing `libpam0g-dev`, the package mentioned by @cylgom, the error was solved and now it is installed (I have not tested Ly yet). I think this dependency should be installed automatically or at least indicated in the README that it is necessary to install it, if not in every case, specify that in some cases.

Thank you for develop this software! I hope it will run nice for me!

**Comment by cylgom** [comment]
@ivanhercaz Done (55fcacb)
