### ISSUE TITLE
Trying to compile on Fedora 30 claims that stropts.h is missing

### ISSUE THREAD

**Issue by ericzx505** [cylgom/ly#104]
When using the instructions in the readme provided, I see that I am missing stropts.h
is this a dependency that I am missing?

error code when running 'make' within the ly folder created by using git clone https://github.com/cylgom/ly.git

`building object obj/src/draw.o
src/draw.c:14:10: fatal error: stropts.h: No such file or directory
   14 | #include <stropts.h>
      |          ^~~~~~~~~~~
compilation terminated.
make: *** [makefile:49: obj/src/draw.o] Error 1`

**Comment by HavenMKing** [comment]
stropts.h is a header that is not included in many modern Linux systems. It is used in ly to display whether the user has capslock and numlock on or not.

If you can live without that, a quick fix you can make to (probably) get it to compile, is removing lines 292 through 351, as well as line 14 in ly/src/draw.c before compiling.

Disclaimer: I have not  tested this solution, and there's probably a more robust solution than going without the lock indicators altogether, but this is a quick and dirty fix.

**Comment by cylgom** [comment]
We don't even need to include this, <sys/ioctl.h> is enough. Thanks for reporting.
@ee41d92
