### ISSUE TITLE
change keyboard layout

### ISSUE THREAD

**Issue by EntityCuber** [cylgom/ly#105]
I am using dvorak keyboard layout in my arch Linux. But ly login manager is in qwerty layout. Is there any option to change or run a command to change keyboard layout using loadkeys?

**Comment by oxodao** [comment]
Ly is console based not X11 so you probably did not set this configuration
Into the `/etc/vconsole.conf` file, add `KEYMAP=yourkeymap`

**Comment by EntityCuber** [comment]
Thank you so much . this works but I did with another method.

"localectl list-keymaps" to list all keymaps

"localectl set-keymap yourkeymap" to set it as system wide
