### ISSUE TITLE
[SOLVED] Fire animation?

### ISSUE THREAD

**Issue by TheBeachLab** [cylgom/ly#106]
How do you guys get the DOOM fire animation working? I set the configuration as stated in the README.md :thinking:

**Comment by oxodao** [comment]
Did you upgrade from an older version of ly (So that you had a previous config file) ?
IDK if it's just the binary that @cylgom gave me or if it's like this on the GH/repositories version but mine came with it auto-enabled

**Comment by usernamewashidden** [comment]
Yep it's a bug. You need both /usr/share/wayland-sessions and /usr/share/xsessions folders on your system to have animation.

**Comment by TheBeachLab** [comment]
thank you! I had /usr/share/xsessions already created. I created /usr/share/wayland-sessions and now I have animation

@oxodao no, it was fresh installation from AUR
