### ISSUE TITLE
Fedora 30 Problems with permissions when using ly

### ISSUE THREAD

**Issue by ericzx505** [cylgom/ly#109]
when using startx /path/to/windowmanager or using other display managers (so far sddm and lightdm) applications that need permissions to do certain actions like file managers mounting drives works as expected. I have tried this with  pcmanfm and nemo so far

when I use ly as the display manager both pcmanfm and nemo give the message
"not authorized to perform action"
when I try to mount an external device

**Comment by cylgom** [comment]
This should be fixed in 4c17b2f, forgot to close (again)
