### ISSUE TITLE
How to logout, lock when lid is closed sleep etc?

### ISSUE THREAD

**Issue by anthr76** [cylgom/ly#110]
Great project ! I'm liking it very much. I was sadly dealing with a bug that caused my boot verbos chatter from grub/arch to be appeared on the login screen but after a clean install it's gone now.

One question though, I'm using i3 on a laptop and I want to have the ability to close my lid or lock my PC for it to return to ly.

What's the best way about going about this? Invoking a script?

**Comment by skidnik** [comment]
Logout must be invoked by your desktop environment or window manager,  for locking the screen you need to invoke a screen locking utility, both have nothing to do with ly. [Tip](https://wiki.archlinux.org/index.php/Power_management#xss-lock)

**Comment by cylgom** [comment]
Yes, this is another thing entirely.
