### ISSUE TITLE
Unicode chars don't work in terminal

### ISSUE THREAD

**Issue by CodeOhms** [cylgom/ly#116]
OS: Manjaro
Arch: x86_64
Window manager: XFCE4

When launching through Ly, unicode characters no longer work in my zsh terminal. It does, however, function if I launch using LightDm. The command I am using to test if unicode characters are available is this:
`echo "\ue0b0 \u00b1 \ue0a0 \u27a6 \u2718 \u26a1 \u2699"`

The error returned:
`zsh: character not in range`

Hopefully this is an easy fix, as this launcher is awesome :+1: .

**Comment by potatoattack** [comment]
I think this has something to do with ly not setting the locale on login.

I have a similar issue with tmux not showing unicode characters which can be solved with:
```export LANG=en_US.UTF-8```
Before launching tmux.

**Comment by inaugur** [comment]
I have the same problem in the zsh. How did you solve the issue?

**Comment by CodeOhms** [comment]
I don't remember the work around, sorry. I think it had something to do with Ly not setting the locale. Try using another session manager, like LighDM, and check to see if unicode characters work. If they do, then your problem is exactly the same as what I had. In this case, look up the commands to see your locale setting and compare it to when you login using Ly. Read this article to have them set when you are using Ly.  https://unix.stackexchange.com/questions/74618/how-to-change-locale-environment-variable

**Comment by potatoattack** [comment]
Try setting your LANG in /etc/environment
I.E put
`LANG=en_US.UTF-8`
in /etc/environment and restart.

**Comment by inaugur** [comment]
My outputs:

`sddm; locale`
LANG=ru_RU.UTF-8
LC_CTYPE="ru_RU.UTF-8"
LC_NUMERIC="ru_RU.UTF-8"
LC_TIME="ru_RU.UTF-8"
LC_COLLATE="ru_RU.UTF-8"
LC_MONETARY="ru_RU.UTF-8"
LC_MESSAGES="ru_RU.UTF-8"
LC_PAPER="ru_RU.UTF-8"
LC_NAME="ru_RU.UTF-8"
LC_ADDRESS="ru_RU.UTF-8"
LC_TELEPHONE="ru_RU.UTF-8"
LC_MEASUREMENT="ru_RU.UTF-8"
LC_IDENTIFICATION="ru_RU.UTF-8"
LC_ALL=

`sddm; locale -a`
C
POSIX
ru_RU.utf8

--------------------------------------------------------------
`ly;  locale`
LANG=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=

`ly; locale -a`
C
POSIX
ru_RU.utf8

**Comment by inaugur** [comment]
`cat /etc/locale.conf`
LANG=ru_RU.UTF-8

**Comment by inaugur** [comment]
Thank you a lot, potatoattack!
Setting `LANG=ru_RU.UTF-8` in `/etc/environment` worked like a miracle!

**Comment by stlaz** [comment]
@cylgom I encountered the same issue, yet with ly versions < 0.3 the locales where always working correctly. Why would additional configuration be necessary now?

**Comment by cylgom** [comment]
Maybe 62c3d70 helps?

**Comment by stlaz** [comment]
Tested and works on my system, thanks!
