### ISSUE TITLE
How to use ly on Void linux (runit)?

### ISSUE THREAD

**Issue by ImagineInfinity** [cylgom/ly#117]

**Comment by gjorando** [comment]
[This fork](https://github.com/drozdowsky/ly-void) uses runit, you can use the runit service configuration files from [there](https://github.com/drozdowsky/ly-void/tree/master/res/ly-runit-service).

**Comment by ImagineInfinity** [comment]
Thank you :)

**Comment by skuzzymiglet** [comment]
I really think this should be included or just linked in this repo. Perhaps `make install` and also `make install-void`
