### ISSUE TITLE
No cursor after exit

### ISSUE THREAD

**Issue by Victor-Bonnelle** [cylgom/ly#118]
Hey! Your DM is just awesome. Really. A simple DM in TUI... Ok, the problem is that if systemctl launches it, there's no problem, there's a cursor, I can connect me. But when I'm connected, if I exit my session (Win+Shit+E in i3 or just `exit` in shell) ly comes again and... No cursor anymore. I can't see on what line I am. I can still write or even select the DE but I can't see where I am anymore. Sorry I don't have anything to provide I really don't know what the problem could be. Of course if you need logs or something feel free to ask. I'm running Arch Linux (I installed it this morning btw so it's almost a fresh install). Thanks for answering ^^

**Comment by gjorando** [comment]
I agree, I have the same issue.

**Comment by nopain2110** [comment]
I have the same issue, too :((

**Comment by Eduarch42** [comment]
Same issue here too.

**Comment by gnull** [comment]
Same issue too. I'm using version `v0.4.0.r2.g7485d89-1` installed from AUR: <https://aur.archlinux.org/packages/ly-git/>.

**Comment by AtkLordOverAll** [comment]
Same here too, using the latest from AUR
