### ISSUE TITLE
KDE

### ISSUE THREAD

**Issue by volfco** [cylgom/ly#12]
I'm having trouble getting KDE to launch via ly.

The Plasma shell shows up in the selection, but upon login, x spews some messages and then quits dumping me back at ly. I've tried putting startkde in .xinitrc, but it either fails or complains about dbus syncing.

Ideas?

**Comment by cylgom** [comment]
Can you dump the complains and spewed messages ? The exact nature of the issue will help ; thank you for reporting ;)
