### ISSUE TITLE
How to handle login session correctly?

### ISSUE THREAD

**Issue by jkrcma** [cylgom/ly#121]
When I use `ly` to log in and start X for me, I can't see my session in `w` or `who` command outputs. It brings problems together with `policykit` where all the default rules concerning suspend or hibernate are bound to local sessions only.

I wasn't figure out whether I am able to force local login session through `xsetup.sh` or PAM. Can you help?

**Comment by inaugur** [comment]
Same issue. Login with sddm and ly makes different situations. Here my outputs (archlinux):

`sddm; w`
23:02:41 up 37 min,  1 user,  load average: 0,96, 1,04, 0,94
USER     TTY        LOGIN@   IDLE   JCPU   PCPU WHAT
myusername   tty1      22:25   37:44   1:10  34.90s awesome

`sddm; who`
myusername   tty1         2019-09-18 22:25 (:0)

`ly; w`
23:04:46 up 0 min,  0 users,  load average: 0,37, 0,09, 0,03
USER     TTY        LOGIN@   IDLE   JCPU   PCPU WHAT

`ly; who`
it prints nothing

**Comment by stlaz** [comment]
This is basically a feature request on adding utmp handling for login accounting, see `man 3 getutxent`

**Comment by evgenux** [comment]
In 0.4.0 issue still exist. Command `w` returns nothing. Due to the problem range of the other programs doesn't work correctly.

**Comment by stlaz** [comment]
@jkrcma @evgenux I opened a PR which should fix this for you, please see whether it does - https://github.com/cylgom/ly/pull/133

**Comment by evgenux** [comment]
Thank you a lot, @stlaz! With #133 login session starts well on my pc. Even my clipmanager, which depends somehow on it, functionate properly.

**Comment by evgenux** [comment]
Thank you a lot, @stlaz! With #133 login session starts well on my pc. Even my clipmanager, which depends somehow on it, functionate properly.

**Comment by evgenux** [comment]
But I noticed another related issue: when I terminate awesome wm (or qtile), a wallpaper remains and I can't get to `ly` again.

**Comment by stlaz** [comment]
If it’s related only to this fix, it might be caused by https://github.com/cylgom/ly/pull/133/files#r339329964. I haven’t tested this with xserver yet, actually.

**Comment by evgenux** [comment]
Yes, it is: I can't get back to `ly` only with #133. But without your patch range of programs doesn't work: for example `connman` rejects to work and prints `Error getting services` etc.

**Comment by evgenux** [comment]
With patch #133 `ecryptfs-add-passphrase` doesn't work.
