### ISSUE TITLE
Access after locking the screen.

### ISSUE THREAD

**Issue by mawbah** [cylgom/ly#124]
I made a mistake in the i3wm configuration file. I registered in it autoloading cmus (console audio player) instead autoloading urxvt with cmus. After authorization cmus load in background, and, when I logout i3, cmus overlap ly on screen, and I can control playlist, switch songs, etc.

**Comment by cylgom** [comment]
I think your configuration had the side-effect of launching cmus within the desktop environment process, after i3 stopped. Nothing to fear, just some i3 black magic.
