### ISSUE TITLE
ly starts tty session

### ISSUE THREAD

**Issue by alexmik95** [cylgom/ly#128]
I'm on archlinux with x11 and openbox. Switched to ly from lightdm.
After logged in there are many things that don't work as plank:
[WARN 14:45:21.737388] [Environment:183] Neither of XDG_SESSION_DESKTOP, XDG_CURRENT_DESKTOP or DESKTOP_SESSION is set in this environment!
[CRITICAL 14:45:21.737524] [AbstractMain:255] Only X11 environments are supported.

I figured out that 'echo $XDG_SESSION_TYPE' return 'tty' at the first login. If I logout and back in 'echo $XDG_SESSION_TYPE' return 'x11'.
I tried to modify /etc/ly/xsetup.sh without success.

**Comment by cylgom** [comment]
This is the same issue as #121, we must implement utmp so fix that (and some other utmp-related issues)
