### ISSUE TITLE
Plasma (Wayland) appears as Plasma

### ISSUE THREAD

**Issue by ericonr** [cylgom/ly#129]
Hi there! I've just started using ly (really loved the fire background, btw), but I have found a small issue in it for my setup. I have both Plasma for Xorg and Plasma Wayland installed in my system. This means that ly shows two sessions with the same name. In this case, Plasma.

What is a reasonable solution for this? Should I just change the name on the session file?

For example, the way SDDM treats this is that it includes `(Wayland)` for every Wayland session. That way, both Sway and Plasma have that extra information. This could be a feature that ly supports as well, perhaps via some configuration setting.

If you come to any decision that involves adding something to ly, I would be interested in implementing it! Thanks for the attention.

PS: This [asciinema](https://asciinema.org/a/6jQ7fJrMg4HcVS3sXOa6dYLQK) shows this issue.

**Comment by cylgom** [comment]
Hi, you are right we should probably do something about this.

I think the best way to achieve what we want is to change the name of the session while reading it from the session file. This can be done by writing another version of `config_handle_str` that appends ` (Wayland)` to the session file's string before saving it. This function is used in `desktop_crawl`, so we need to add a condition here.

However, some desktop environments already include ` (Wayland)` in their session file, so the new `config_handle_str` should read the input string and check if it doesn't end with something similar.

You can find the config handles and configuration options in `config.c`.
Feel free to ask any question if something is unclear :)

**Comment by ericonr** [comment]
Wow, sorry for the delay. School has been crazy! Do you think there should be a config option to determine if we add `(Wayland)` to the session name?

**Comment by ericonr** [comment]
Well, this one's done! I will close it :)
