### ISSUE TITLE
"Pam Transaction Aborted"

### ISSUE THREAD

**Issue by davedorm** [cylgom/ly#13]
Not sure what I am doing wrong. Everything comes up as it should. When it fails on that tty, I can switch to another and login. Any idea what I'm missing?

**Comment by cylgom** [comment]
Hi, you're not the first one to have this issue #2, it's likely to come from your pam setup.
Please check if ly can access "pam_loginuid.so" (you can try making a symlink at "/lib/pam_loginuid.so").
