### ISSUE TITLE
Rename margin to padding in config

### ISSUE THREAD

**Issue by KargJonas** [cylgom/ly#131]
I believe the naming of the `margin_box_h` and `margin_box_w` is technically incorrect as they affect the padding of the window instead of the margin. I'd suggest renaming them to `padding_box_w` and `padding_box_h`.

I will create a PR as soon an possible   :D

**Comment by cylgom** [comment]
Waiting for the PR then :)

**Comment by KargJonas** [comment]
Oh geez I forgot this 😅
