### ISSUE TITLE
Does not load DE or WM

### ISSUE THREAD

**Issue by MrMip** [cylgom/ly#132]
It give me a list of all the desktop environment and window managers I have installed, but when I try to login to any of them (inclining shell) it just gives me a blinking cursor or it just does not login and sits there.

Distro: Fedora 30

**Comment by cylgom** [comment]
This is what happens when the environment is not set up properly. Maybe utmp will help (#121), or maybe I missed something

**Comment by MrMip** [comment]
I did nothing. The same problem still consists. :(

**Comment by UltimaQuazar** [comment]
I have tried the UTMP audit branch from stlaz.
It still shows the blinking cursor on Fedora 30. 
I keep getting an issue of it not being able to open the display. 

`OS: Fedora 30`
`Kernel: Linux 5.3.11-200.fc30.x86_64`

**Comment by cylgom** [comment]
Could you try again now #121 is really fixed?
