### ISSUE TITLE
Backspace changing textfields

### ISSUE THREAD

**Issue by L0ric0** [cylgom/ly#14]
When one deletes the hole password field, the courser jumps to the username field.

**Comment by oxodao** [comment]
That's intended, that's how ncurses works

**Comment by cylgom** [comment]
I'll take a look, but oxodao is right : this is the default behaviour of the library I use.

**Comment by AlexKornitzer** [comment]
@cylgom @oxodao, any chance that you can merge @djpohly's changes or are there reasons you have not?

**Comment by oxodao** [comment]
I do not have any access to the repo so I won't merge it, and cylgom is quite busy. I will try to contact him today.

**Comment by AlexKornitzer** [comment]
Ah awesome, many thanks, as they appear to fix a few issues I have with what is otherwise an awesome bit of code :)
