### ISSUE TITLE
Adding Ly to the FreeBSD Ports Collection

### ISSUE THREAD

**Issue by 0mp** [cylgom/ly#143]
I've posted initial patches adding Ly to FreeBSD Ports. If anyone is interested in helping out then the patch is available here: https://reviews.freebsd.org/D22228

**Comment by drozdowsky** [comment]
https://github.com/cylgom/ly/issues/113

**Comment by 0mp** [comment]
Thanks, @drozdowsky. I added your suggestions to the port. Now I can see Ly after boot but I cannot log in. Could you test out that ports patch?

**Comment by drozdowsky** [comment]
Currently I run my fork of https://github.com/drozdowsky/ly-void/ (10 commits behind) so maybe that's it. Tomorrow I will have access to my FreeBSD laptop so I can check out port and/or try to rebase my fork

**Comment by drozdowsky** [comment]
After rebase'ing I can not log in too. It has been probably introduced in last 10 commits.

**Comment by 0mp** [comment]
I am using the last common version of Ly and the fork of @drozdowsky. I can log in into a **shell** session but both **awesome** and **dwm** seem somewhat broken: the keyboard is busy printing "w" letters (you may observe it in Awesome WM after launching a terminal and then focusing your cursor on it). FYI, I had to remove the login.c patch (from #113) in order to make it work like this.

Do you have any other non-default configurations in your /etc/ttys?

**Comment by drozdowsky** [comment]
do you have mcookie?
`which mcookie`
it is linux-util tool

I have script for that in /usr/local/bin/mcookie
`#!/bin/sh
dd if=/dev/random bs=16 count=1 2>/dev/null | od -x -An | tr -d ' '
`

**Comment by 0mp** [comment]
Have you got any idea how the login.c patch is solving the keyboard problem for you? It looks like you are just hard-coding Ly to use vt04 no matter what's the value of tty in config.ini. Could you please explain a little bit the reasoning here? Thanks :)

**Comment by drozdowsky** [comment]
It was just a guess, I have assumed that non working keyboard is related to tty switch. I do not remember it fully tbh, probably I wasn't sure if value from config is used anywhere else so I tried that.
Trial & error method tbh

**Comment by 0mp** [comment]
I got it working yesterday. I'll try to upstream my changes soon. Basically, Ly should not try to start the X server on the very same tty it is running itself. This is why your patch is working.

Thanks a lot for all you help ;)

**Comment by 0mp** [comment]
Ok, the port patch is awaiting the final round of reviews & testing: https://reviews.freebsd.org/D22228

**Comment by drozdowsky** [comment]
I will test it for sure soon

**Comment by 0mp** [comment]
Nice, let me know if everything is working fine in your setup.

**Comment by drozdowsky** [comment]
works fine, thank you!
though I saw one mistake thing in xsetup.sh
```
 if [ -d $$LOCALBASE%%/etc/X11/Xresources ]; then
```
One think I do not like:
```
.0  0:00.00    │     ├─ /usr/local/bin/oksh -c /usr/local/etc/ly/xsetup.sh ~/.xinitrc
.5  0:02.34    │     │  └─ /usr/local/bin/awesome
.0  0:00.00    │     └─ /usr/local/bin/oksh -c /usr/local/bin/X :0 vt9
.8  0:09.28    │        └─ /usr/local/bin/X :0 vt9
```
there is no need to run xsetup with user shell, maybe it is upstream issue but on the other hand we are sure in FreeBSD that we have /bin/sh

cool thing to have would be ly_enable=Yes, you have probably thought about this.
Port looks great, nice job :)

**Comment by 0mp** [comment]
> works fine, thank you!
> though I saw one mistake thing in xsetup.sh
> 
> ```
>  if [ -d $$LOCALBASE%%/etc/X11/Xresources ]; then
> ```

Uh, nice catch!

> One think I do not like:
> 
> ```
> .0  0:00.00    │     ├─ /usr/local/bin/oksh -c /usr/local/etc/ly/xsetup.sh ~/.xinitrc
> .5  0:02.34    │     │  └─ /usr/local/bin/awesome
> .0  0:00.00    │     └─ /usr/local/bin/oksh -c /usr/local/bin/X :0 vt9
> .8  0:09.28    │        └─ /usr/local/bin/X :0 vt9
> ```
> 
> there is no need to run xsetup with user shell, maybe it is upstream issue but on the other hand we are sure in FreeBSD that we have /bin/sh

Actually, I think this is on purpose. This we xsetup.sh is able to load configs for your shell (in your case that would be only .profile and /etc/profile).

> 
> cool thing to have would be ly_enable=Yes, you have probably thought about this.
> Port looks great, nice job :)

I've not figured out yet how to just spawn ly as daemon service properly. ;) Patches definitely welcome.

**Comment by 0mp** [comment]
Aaand Ly is now available in FreeBSD ports: https://www.freshports.org/x11/ly/

It should be available soon in the package repo (at least on the *latest* branch).

Thanks A LOT for your help. ;)
