### ISSUE TITLE
Garbage after run .xinitrc

### ISSUE THREAD

**Issue by hk0kizu** [cylgom/ly#144]
I get much a X-log after run xinitrc on ly lockscreen.
Is [https://github.com/cylgom/ly/issues/42](url) it related? 
>Before compilation add -keeptty > ~/.xorg.log 2>&1 to the end of the LY_CMD_X line so it reads #define LY_CMD_X "/usr/bin/X -keeptty > ~/.xorg.log 2>&1"

I trying add `x_cmd = /usr/bin/X -keeptty > ~/.xorg.log 2>&1` in config.ini, but nothing good.

**Comment by cylgom** [comment]
I had luck with `x_cmd = /usr/bin/X -keeptty > /home/cylgom/.xorg.log 2>&1`, this is likely on your side :/
