### ISSUE TITLE
Unsubmodule Ly

### ISSUE THREAD

**Issue by tim77** [cylgom/ly#147]
Hello. Ly look interesting project, but submodules and build process prevent to include Ly in official repo of some major distros, so is it possible to improve this situation? Really want to package it for Fedora. Thank you.

**Comment by 0mp** [comment]
FYI, I've almost finished packaging it for FreeBSD (see #143), I am testing the Ly itself now.

**Comment by cylgom** [comment]
I don't really think this would be an improvement, sorry...
