### ISSUE TITLE
Doesn't change language when lang is uncommented in config.ini

### ISSUE THREAD

**Issue by ivanhercaz** [cylgom/ly#151]
I translated Ly to Spanish and propose #150 to merge it, but as I commented in the PR I couldn't test if the strings are fine by myself looking them in the screen. At the first time I thought that it may be caused by something I forgot to do or didn't that I should do before to configure it, but I set the French language in the config and it didn't work either.

Any idea about it?

**Comment by ivanhercaz** [comment]
Hi @Cylgon! Any idea about it? :no_mouth:

**Comment by ivanhercaz** [comment]
Hi @Cylgom! Any idea about it? :no_mouth:

**Comment by cylgom** [comment]
Fixed in 676cbf5 :)

**Comment by ivanhercaz** [comment]
> Fixed in [676cbf5](https://github.com/cylgom/ly/commit/676cbf55a880b1b5204620e2d534aa9b5073a807) :)

Really nice! I will test it as soon as possible. Thank your for your awesome work.
