### ISSUE TITLE
Fail to run `make` on CentOS

### ISSUE THREAD

**Issue by dipu-bd** [cylgom/ly#156]
I tried setting up this DM in CentOS 7. But `make` fails with following error:

```
building object obj/src/main.o
src/main.c: In function ‘main’:
src/main.c:191:5: error: implicit declaration of function ‘usleep’ [-Werror=implicit-function-declaration]
     usleep(10000);
     ^
cc1: all warnings being treated as errors
make: *** [obj/src/main.o] Error 1
```

**Comment by Kostrak** [comment]
I looked around the internet and I believe the fastest and easiest solution would be adding <include unistd.h> into the main.c file, because that's where usleep() is declared.

**Comment by dipu-bd** [comment]
I had some dependency issue. Now it is working properly after I upgraded them.
