### ISSUE TITLE
Support for Ctrl+u to discard current text

### ISSUE THREAD

**Issue by mwiens91** [cylgom/ly#166]
I've looked around to see if this exists but couldn't find anything. Often times when I'm entering a password I'll make a mistake and, at least on a terminal, would type Ctrl+u to remove the text and start over. This isn't supported out of the box by Ly, though it is supported by other display managers I've used.

Does an option for this exist in Ly? If not, how much work is it to add this feature?

**Comment by cylgom** [comment]
Added in 7fd849d81e2249f3ad6868333502f504b3402d7d, thank you for the suggestion :)
