### ISSUE TITLE
Xorg settings dont load X11/xorg.conf.d

### ISSUE THREAD

**Issue by demeere** [cylgom/ly#171]
Hello. Somehow the files in xorg.conf.d don't get loaded although they should be loaded automatically. 
My monitor config and xorg keyboard layout is dependent on these files.  
It worked in lightdm though.
Is this just an error in my site? And if so how can I fix it?

**Comment by cylgom** [comment]
It loads fine on my system, the error likely has another cause (maybe still in Ly). You can open another ticket when you figure it out :)

**Comment by demeere** [comment]
Thanks for the reply.
Well, I just tried directly launching i3 with xinitrc -I just put exec i3 in there and it seems to result in the same issue.
I just dont understand it worked perfectly fine with lightdm...

**Comment by demeere** [comment]
https://wiki.gentoo.org/wiki/Xorg/Guide#The_xorg.conf.d_directory
I looked up pretty much everything ...without results

**Comment by demeere** [comment]
found the solution
I just copied the files to /usr/share/X11/ instead of /etc/X11
