### ISSUE TITLE
Sway support

### ISSUE THREAD

**Issue by andersfylling** [cylgom/ly#18]
Just started using this, and would love to see sway support ^^,

**Comment by oxodao** [comment]
This software is fully based around Xorg so I don't think it will happens anytime soon, but that would be neat indeed to support Wayland

**Comment by cylgom** [comment]
Actually this was planned, but my CG refuses to launch wayland currently.

**Comment by cylgom** [comment]
Ok, as my GC unexpectedly started working with Wayland so I added Wayland support. I have a few major issues though: sway starts on the wrong screen and freezes instantly. But I have optimus on my laptop: Could you try it and tell me if you have more luck with it ? Thank you!

**Comment by andersfylling** [comment]
Oh sorry, I installed a different distro with Xorg a month ago :/

**Comment by Roshless** [comment]
Doesn't seem to work (sway-git, ly-git)
Did you include wayland support in the rewrite?

**Comment by cylgom** [comment]
No I didn't because my laptop has an nvidia graphics card with optimus, which makes testing difficult. To stay polite nvidia does not support wayland, so I can't experiment easily. Support will come if nvidia change their mind (which they won't) or when I buy a new, full-amd computer.
