### ISSUE TITLE
Missing argoat.h

### ISSUE THREAD

**Issue by RandomGuyDTB** [cylgom/ly#188]
System: Debian 10 "Buster" amd64 cleanly installed on a Thinkpad T420; i5-2540M, iGPU, 16GB RAM.

I'm getting a build error when running `make`:
```
building object obj/src/main.o
src/main.c:1:10: fatal error: argoat.h: No such file or directory
 #include "argoat.h"
          ^~~~~~~~~~
compilation terminated.
make: *** [makefile:52: obj/src/main.o] Error 1
```
I did some research and it looks like argoat is [your own project](https://github.com/cylgom/argoat). Might wanna add argoat to the source for ly so people don't have to download argoat separately.

**Comment by jkrcma** [comment]
Did you run `make github` before?

**Comment by RandomGuyDTB** [comment]
Well, looks like I'm a bit of a goof. `make github` fixes the problem. Next time I'll re-read the instructions.

**Comment by AntonSever** [comment]
The same error:

> $ make                                                                                                                                                                                    
fatal: not a git repository (or any of the parent directories): .git
building object obj/src/main.o
src/main.c:1:10: fatal error: argoat.h: No such file or directory
    1 | #include "argoat.h"
      |          ^~~~~~~~~~
compilation terminated.
make: *** [makefile:52: obj/src/main.o] Error 1

> $ make github                                                                                                                                                                             
make: *** No rule to make target 'github'.  Stop.

**Comment by isXander** [comment]
`make github` doesn't exist anymore.

**Comment by devenblake** [comment]
See the comments on [commit a20d5195a65f2fb67718435225efffa02b81d1bc](https://github.com/fairyglade/ly/commit/a20d5195a65f2fb67718435225efffa02b81d1bc) where the updated way to fetch the submodules is explained. The new method is to clone the repository with `--recurse-submodules`:

`git clone --recurse-submodules https://github.com/fairyglade/ly.git`

**Comment by isXander** [comment]
Whoops. Did it with GitHub cli.
