### ISSUE TITLE
Define a unique service name for PAM.

### ISSUE THREAD

**Issue by skidnik** [cylgom/ly#189]
**Currently** when calling PAM ly specifies it's service name as 'login'. At least as far as I understand [this](https://github.com/cylgom/ly/blob/master/src/config.c#L288) ( that variable is passed to pam_start() ). 'login' is a `/usr/bin/login` binary and an already taken service name in PAM base configuration, it is used when logging in to tty.

**Expected** to specify a unique service name, e.g. 'ly' to allow creating a specific for this service configuration for PAM e.g. `/etc/pam.d/ly`.

From [PAM developer docu](http://www.linux-pam.org/Linux-PAM-html/adg-interface-by-app-expected.html):

> The service_name argument specifies the name of the service to apply and will be stored as PAM_SERVICE item in the new context. The policy for the service will be read from the file /etc/pam.d/service_name or, if that file does not exist, from /etc/pam.conf.

Why? For example if you want to unlock gnome-keyring or kwallet, a display manager PAM config is the right place to do this.

**Proposed solution:** Replace 'login' with 'ly' in the service name for PAM, ship a boilerplate `/etc/pam.d/ly` config file containing:

```
#%PAM-1.0

auth       include      login

account    include      login

password   include      login

session    include      login
```

The above will not change current behaviour of PAM regarding ly. 

Or refer to how other DMs do this and why, distro packagers change PAM configuration anyway.

Update: proposed changes work fine: session starts normally, changes to `/etc/pam.d/ly`  work: e.g. Gnome keyring unlocks automatically if configured.

Tested on Archlinux, **ly-git** aur package, by adding `sed -i '/config.service_name/s/login/ly/' src/config.c` to prepare() section and manually creating `/etc/pam.d/ly` file with stated above contents.

**Comment by cylgom** [comment]
Thank you very much for this detailed explanation. Fixed as of e36e4b1.
