### ISSUE TITLE
Change font

### ISSUE THREAD

**Issue by vulf** [cylgom/ly#199]
Hi there, 
I'm new to Arch and I really liked the minimalistic nature of ly. But I want to know how I can change the default font. 

Thank you

**Comment by pranavsivvam** [comment]
And also, is it possible to make it the lockscreen too? If yes, please tell me how I can do that.
Thanks

**Comment by dvogit** [comment]
You can't do that, ly is only in the console. You can change your console font, if you wanted.

**Comment by cylgom** [comment]
As @dvogit said, this is not to be expected from a tty program :)
