### ISSUE TITLE
Pam transaction aborted

### ISSUE THREAD

**Issue by ralpheeee88** [cylgom/ly#2]
After inputting credentials I get the above mentioned error (arch)

**Comment by cylgom** [comment]
This means one of the pam transactions encountered a critical error without other details being available. Please check your pam configuration and pam modules. You can also verify if a link to "/usr/lib/security/pam_loginuid.so" was made at "/usr/lib/pam_loginuid.so". The error is likely to come from your pam installation. Thank you for reporting this; keep me informed.

**Comment by ralpheeee88** [comment]
@cylgom http://ix.io/uLV

**Comment by cylgom** [comment]
Then it's likely to come from your pam installation. Can you check if ly can access to "pam_loginuid.so" ?
You can also try to make another link at "/lib/pam_loginuid.so". This kind of problem can also appear if the username contains a space or if the user doesn't exist.
