### ISSUE TITLE
default configuration causes segfault on out-of-the-box systems

### ISSUE THREAD

**Issue by dglanzman** [cylgom/ly#20]
at ncui.c:44 we call fopen then immediately fclose the returned handler. The default location for the file is /etc/ly/ly.save. The /etc/ly directory doesn't exist unless it is manually created beforehand. If /etc/ly is not previously created, the call to fopen will return a null file handler, which causes a segfault in the subsequent fclose.

I propose either the default location for ly.save is changed to a location that exists by default, or instructions are added to the README to explicitly create /etc/ly beforehand or manually change that config option.

**Comment by oxodao** [comment]
If i'm not mistaken ly runs as root when you starts up your machine. 
Why not just create it then ?

**Comment by dglanzman** [comment]
That's another valid option.

**Comment by le34n** [comment]
Will not it be more correct to place the /etc/ly/ly.save in a /var/lib/ly/ly.save ?
Temporary files are best practic stored in the /var directory.

**Comment by cylgom** [comment]
This is now fixed thanks to the above PR, closing
