### ISSUE TITLE
Preselect Xinitrc and user

### ISSUE THREAD

**Issue by rudolfschmidt** [cylgom/ly#208]
The only reason I want to use a login manager is to not type my username and after login to type startx. But I want my xinit get started (and I see you have a proper session to select for it).

So how to preselect a default user (me) and how to preselect xinitrc as the default launch session?

**Comment by cylgom** [comment]
Ly will save the last user and desktop and load them back automatically by default. You can disable this by changing `save` to `false` in `/etc/ly/config.ini`: in this case the last saved login and desktop will be loaded but can't be changed by the user.
