### ISSUE TITLE
stucks when power plug insertion ACPI event happens

### ISSUE THREAD

**Issue by qub1750ul** [cylgom/ly#21]
The following string is printed on the screen and then ly freezes.
[ 9910.556531 ] acpi INT3400:00: Unsupported event [ 0x86 ]

Then the only way to make ly work again is to restart the relative unit via another tty.
Other events also write on the screen but doesn't affect ly.

**Comment by cylgom** [comment]
Could you try compiling the latest version and report if this is still happening? Thank you for your help!

**Comment by qub1750ul** [comment]
Installed latest version using ly-git aur package after a full system upgrade.
Now the acpi string doesn't show anymore, but when i insert the power plug the cursor goes in low left of the screen and then ly stop reacting to keypresses.

**Comment by cylgom** [comment]
I think it's not Ly's fault, can you check your /etc/systemd/logind.conf and try again after setting the event to "ignore" ?

**Comment by qub1750ul** [comment]
This is xev's output when the plug is inserted, maybe it can be useful:
```
MappingNotify event, serial 58, synthetic NO, window 0x0,
    request MappingKeyboard, first_keycode 8, count 248

KeyPress event, serial 58, synthetic NO, window 0x3200001,
    root 0x199, subw 0x0, time 9313421, (106,89), root:(157,498),
    state 0x0, keycode 248 (keysym 0x0, NoSymbol), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyRelease event, serial 58, synthetic NO, window 0x3200001,
    root 0x199, subw 0x0, time 9313421, (106,89), root:(157,498),
    state 0x0, keycode 248 (keysym 0x0, NoSymbol), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False
```

**Comment by qub1750ul** [comment]
I think i've managed to fix this.
To confirm my assumptions can you explain what's the purpose of the condition in
src/main.c, line 95
```while((input_key = wgetch(win.win)))```

Other than acquiring user input it is meant to terminate the program if an input error occurs, right ?
