### ISSUE TITLE
Cannot start i3

### ISSUE THREAD

**Issue by GrbavaCigla** [cylgom/ly#214]
When I enter the session, username and password it waits for a second and then displays login again. Before it worked fine, now only login to shell works. Also when I logout it doesn't display ly.

**Comment by dvogit** [comment]
Add i3 to your `~/.Xsession` or `~/.xinitrc`

**Comment by GrbavaCigla** [comment]
I added `exec i3` in ~/.xinitrc but it still doesn't work. Before, when I select i3, it worked perfectly, now only shell works.

**Comment by anntheknee** [comment]
Same issue here with dwm. `exec dwm` at last line of `~/.xinitrc` and it just automatically logs me out to ly.

**Comment by anntheknee** [comment]
@GrbavaCigla Did some investigation work and turns out while `.xinitrc` may be executable with the shebang, it needs executable permissions e.g. `sudo chmod +x ~/.xinitrc`. Worked for me with dwm.

**Comment by GrbavaCigla** [comment]
Weird, I already done that and it still doesn't work. When you log in and select session, do you select `xinitrc` or `dwm` ?

**Comment by anntheknee** [comment]
I'm selecting `xinitrc`. For some reason, `dwm` doesn't appear as a session for me - only have `xinitrc`, `shell`. and `Plasma`.

**Comment by GrbavaCigla** [comment]
There is configuration in /etc/ly/config.ini, you can uncomment xsession line in the end for it to detect `dwm`. But for me neither `xinitrc` or `i3` works. Can you send me your xinitrc? Maybe I am doing something wrong.

**Comment by anntheknee** [comment]
Ah, thanks for the heads up! I just copied the default one at `/etc/X11/xinit/xinitrc`, deleted the last 5 or so lines and added `exec dwm`.

```
#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then

    xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fia

if [ -f "$userresources" ]; then

    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

exec dwm

```

**Comment by GrbavaCigla** [comment]
Still doesn't work, probably caused by something else in the system. Anyways thanks for helping me.
