### ISSUE TITLE
[REDAME] Missing dep on Debian based

### ISSUE THREAD

**Issue by IGLOU-EU** [cylgom/ly#218]
Hi,    
On Debian based distros xcb.h doesn't come with xcb package    
You need to install `libxcb-xkb-dev`    

Thanks ＼(＾▽＾)／

**Comment by devenblake** [comment]
Mentioned this previously in #210 and made a pull request to go along with it.

**Comment by cylgom** [comment]
Fixed, thanks for reporting :)
