### ISSUE TITLE
make it work with kmscon as the console!

### ISSUE THREAD

**Issue by 257** [cylgom/ly#22]
kmscon is dead, granted, but it is functional...

kmscon can replace kernel's VT and ly actually looks great on kmscon.

the way i have been testing so far has been to replace agetty with kmscon and login with ly. here is my override.conf for gett@.service
```
[Service]
ExecStart=
ExecStart=/usr/bin/kmscon -v --hwaccel --drm "--gpus=all" "--vt=%I" --no-switchvt --login -- /usr/bin/ly
```
this might require ly to be able to parse command line options and so on, in particular for passing VT to ly.

**Comment by cylgom** [comment]
I actually don't hav any plans on supporting kmscon, but thank you for your interest. If you have detailed explanations on how to get it to work I can write them in the readme however.
