### ISSUE TITLE
DBus

### ISSUE THREAD

**Issue by oxodao** [cylgom/ly#3]
Please add DBus support so that it autostart on login
See https://github.com/davvid/lightdm/search?q=dbus&type=Code&utf8=%E2%9C%93 ?

**Comment by cylgom** [comment]
Done, thanks for the suggestion bro ;) 6e7ceadf1158dd33de348b9ff89ae60126d622b2

**Comment by 257** [comment]
dbus handling is removed, why? please reopen.
this might help: [https://lists.freedesktop.org/archives/systemd-devel/2015-January/027711.html](https://lists.freedesktop.org/archives/systemd-devel/2015-January/027711.html)

**Comment by 257** [comment]
nvm, environment stuff from systemd (interesting to look into nonetheless) is broken for the version i'm running. (one bad env var will freez systemd!). sorry for the noise.
