### ISSUE TITLE
Problems with starting xorg

### ISSUE THREAD

**Issue by Chrysostomus** [cylgom/ly#31]
All xorg based options seem to fail when using ly. It seems to be some kind of permissions issue:

`xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
`

The issue happens only with ly, manual startx and other displaymanagers seem to work fine. Logging into console with ly also works. 

Using the version packaged in AUR: 

https://aur.archlinux.org/packages/ly-git

**Comment by cylgom** [comment]
I don't have any issue with up-to-date packages, can you detail the issue ?

**Comment by le34n** [comment]
I confirm.
Only the login to the console works.
In other cases, a black screen.

**Comment by oxodao** [comment]
Not sure if it's related though, lately my setup takes ages on the console screen before showing ly. Maybe the services takes longer to load but I don't know why they would

**Comment by le34n** [comment]
Here's the output when the black screen:
`$ ps aux | grep X 
testuser       929  0.0  0.0  16040  1100 tty2     S+   20:41   0:00 xinit /etc/ly/xsetup.sh /usr/bin//usr/bin/openbox-session -- /usr/bin/X :0 vt2 -auth /home/testuser/.lyxauth
root       938  0.2  0.2 245400 44872 tty2     Sl   20:41   0:00 /usr/lib/xorg-server/Xorg :0 vt2 -auth /home/testuser/.lyxauth`

**Comment by le34n** [comment]
I tried running from the command line:
`$ xinit /etc/ly/xsetup.sh /usr/bin/openbox-session -- /usr/bin/X :0 vt2 -auth /home/testuser/.lyxauth`
Also black screen.
But then I came up with the idea of adding sudo. 
Like this:
`$ sudo xinit /etc/ly/xsetup.sh /usr/bin/openbox-session -- /usr/bin/X :0 vt2 -auth /home/testuser/.lyxauth`
And it all worked.

**Comment by le34n** [comment]
Solved.
`$ cat .xsession`
`#!/bin/sh`
`/bin/bash --login -i ~/.xinitrc`

`$ rm -f ~/.xsession`

**Comment by cylgom** [comment]
The issue comes from your .xsession, not from ly. I will add warnings about potentially interfering files in the readme for the next version

**Comment by ZanSara** [comment]
@le34n I had a very similar issue and after modifying the source as you mention, ly manages to login, but my .xinitrc is being ignored. How did you solve this issue (if you had it)?
