### ISSUE TITLE
About releases

### ISSUE THREAD

**Issue by Fnux** [cylgom/ly#34]
Hello,

Do you plan to do some kind of releases ? There is this `v0.0.1` in the readme but no associated tag.
I tend to package everything: it would make things easier :-)

**Comment by oxodao** [comment]
I agree it would be better, especially for standard distros such as Debian or Ubuntu that do not relies on automagically building from the AUR

**Comment by Fnux** [comment]
I am packager for Fedora, and will most likely package ly in copr (~= AUR for Fedora) if I really start to use it.

If everything goes smoothly, I might even submit it to the official repositories :-)

**Comment by oxodao** [comment]
Let's hope so :+1: 
I will talk with @cylgom about this asap

**Comment by cylgom** [comment]
I'll see what I can do, there might be a lot of stuff to enhance before releasing. In particular I planned to support Wayland when I started writing ly (which should be very easy), but by nvidia CG doesn't seem to appreciate that.

**Comment by cylgom** [comment]
Ok, I have a few more changes to push in order to make Ly more forgiving about weird acpi events and shell configurations. After that, it will probably be ok. It will be interesting to ask a lot of people who were having X starting issues once I do that, to confirm it works for everyone.

**Comment by Anachron** [comment]
Please create a first release so we can package this upstream.

**Comment by cylgom** [comment]
Here you go https://github.com/cylgom/ly/releases/tag/0.1 thanks for your interest :)

**Comment by Fnux** [comment]
I built a simple package for fedora, available in copr: https://copr.fedorainfracloud.org/coprs/fnux/ly/

If everything goes well during the next few weeks, I might improve the package and push it to the officiel repositories.

Do you have a target for the next release ? I'd like to see #47 fixed in a stable release.

**Comment by cylgom** [comment]
Here's v0.2, using the new codebase which fixes a ton of bugs https://github.com/cylgom/ly/releases/download/0.2/ly_0.2.zip
