### ISSUE TITLE
not working for me :(

### ISSUE THREAD

**Issue by coopj121** [cylgom/ly#37]
● ly.service - ly ncurses display manager
   Loaded: loaded (/usr/lib/systemd/system/ly.service; enabled; vendor preset: disabled)
   Active: failed (Result: core-dump) since Sat 2018-06-30 16:30:23 BST; 18min ago
  Process: 6730 ExecStart=/usr/bin/ly (code=dumped, signal=SEGV)
 Main PID: 6730 (code=dumped, signal=SEGV)

Jun 30 16:30:23 pluto systemd[1]: Started ly ncurses display manager.
Jun 30 16:30:23 pluto systemd[1]: ly.service: Main process exited, code=dumped, status=11/SEGV
Jun 30 16:30:23 pluto systemd[1]: ly.service: Failed with result 'core-dump'.

I'm not sure why it's not working? can you help please

**Comment by AlexKornitzer** [comment]
Hey, I just rebuilt yesterday and I am now getting a core dump, the same as above. I believe your latest commit may be the culprit.

**Comment by lll2yu** [comment]
I tried building with [`c5f0d28`](https://github.com/cylgom/ly/commit/c5f0d28481815036b4fecb6aa963cc3777002c0a), and it works. Got core dump with [`060184b`](https://github.com/cylgom/ly/commit/060184bcb4495e307a6744aa7561054b4f5b6830). 

I'm on zsh.

**Comment by coopj121** [comment]
I'm using bash. Sorry for the late reply

**Comment by AlexKornitzer** [comment]
It is unlikely to be the shell as this is loaded after a user logs in. As @lll2yu has tested the commits it is most likely the wayland support. @cylgom could you revert this commit so that aur works again, or maybe pin aur to a release version?

**Comment by oxodao** [comment]
And tagging it as 0.1 on GH would be a great idea

**Comment by cylgom** [comment]
Ok, I think it is safe to close this one now
