### ISSUE TITLE
[Solved] X.org fails to start when using xinitrc

### ISSUE THREAD

**Issue by lll2yu** [cylgom/ly#40]
According to the issue https://github.com/dunst-project/dunst/issues/347 I need to add `systemctl --user import-environment DISPLAY` to the `.xinitrc` of the user in order to correctly start [dunst](https://github.com/dunst-project/dunst ) dbus service and use it. 
But ly fails to start x (gets stuck on a black screen) when this environment variable is added to the `xinitrc`.
Is there any workaround possible to make it work?

**Comment by qub1750ul** [comment]
try
~~~
systemctl --user import-environment DISPLAY XAUTHORITY

if command -v dbus-update-activation-environment > /dev/null 2>&1 ; then
         dbus-update-activation-environment DISPLAY XAUTHORITY
fi
~~~

**Comment by lll2yu** [comment]
Thanks, that worked. Closing this here.
