### ISSUE TITLE
Possibly logged in as sudo

### ISSUE THREAD

**Issue by mcolligan** [cylgom/ly#41]
Hey, this is really cool and I got it mostly working!
I installed it from the AUR, ran `sudo systemctl enable ly.service` and it appeared to work perfectly.

However, I noticed that I cannot directly run things in ~/bin, despite ~/bin being in $PATH. `whoami` outputs the expected user 'm'.

If I `touch test` and `ls -al test` then I get: 
`-rw-r--r-- 1 m m 0 Jul 24 21:35 test`.

If I do `su m` then I _can_ run things in ~/bin directly. 

Is there some point in the login process or ly setup that could be responsible for this?
Thanks again for a great package.

**Comment by mcolligan** [comment]
I think I had misunderstood how ls outputs permissions information.
`-rw-r--r--`
is actually what you would expect, so that information is not relevant and not a problem. Still strange about the path thing. That seems to be the only issue.

**Comment by RobertZenz** [comment]
> However, I noticed that I cannot directly run things in ~/bin, despite ~/bin being in $PATH.

The error message would have been useful to know.

 > If I do su m then I can run things in ~/bin directly.

Wild guess, your path is wrong.

**Comment by mcolligan** [comment]
Hey - re-reading I definitely missed out a critical part that I was having problems mostly with running things from keyboard shortcuts in i3, my bad. This is why I had no error messages. I just re-installed and I can run these fine if I put the whole path ~/bin/whatever in my i3 config - though this was not needed without ly. My $PATH is set in ~/.zshrc, which is run when I login, and normally I would run startx from there, so the shortcuts would work without full paths. I am guessing that ly is bypassing that altogether and goes straight to running .xinitrc. 

Does this make sense? Does it run .bashrc or anything where I could (if I really needed to) change the path?

Thanks!

**Comment by mcolligan** [comment]
OK, problem solved. 
My last comment was right in that my path was set in .zshrc which was no longer being called before the log in. I moved the line that sets my path into .xinitrc rather than .zshrc and now it works fine.

Thanks again for the great login manager!

**Comment by RobertZenz** [comment]
You most likely want `~/.profile` anyway for that.
