### ISSUE TITLE
Suppress xinitrc output to tty

### ISSUE THREAD

**Issue by SirWindfield** [cylgom/ly#42]
I normally just typed startx into the tty to start my DE. But now since I use ly I wanted to make it look a little bit smoother. Is it somehow possible to make ly not output to the tty when starting using xinitrc? 

I'm not sure if this has something to do with my xinitrc or not. I run the following to start i3: `exec i3 > /dev/null 2>&1`

**Comment by zackarymoore** [comment]
This actually is a fairly straightforward fix. Before compilation add `-keeptty > ~/.xorg.log 2>&1` to the end of the LY_CMD_X line so it reads `#define LY_CMD_X "/usr/bin/X -keeptty > ~/.xorg.log 2>&1"` I'm also running i3 and this has made for an entirely silent login/logout.

**Comment by SirWindfield** [comment]
wow that actually fixed. Thanks very much!
Is that the command ly runs to start x?

**Comment by cylgom** [comment]
fixed in upcoming version

**Comment by zackarymoore** [comment]
> wow that actually fixed. Thanks very much!
> Is that the command ly runs to start x @zackarymoore?

Yes it is, just make sure if you reinstall in the future to add that in before compiling.
