### ISSUE TITLE
HiDPI support

### ISSUE THREAD

**Issue by tammar96** [cylgom/ly#43]
Is there any way to support HiDPI displays?

**Comment by tammar96** [comment]
When using consolefont for HiDPI `latarcyrheb-sun32` I can only see the left top quarter of the UI.

**Comment by oxodao** [comment]
On my desktop computer it also do not center at all

**Comment by cylgom** [comment]
This is likely caused by the tty not detecting the correct screen size, I unfortunately have no idea on how to fix that :(

**Comment by tammar96** [comment]
Is there any way to manually change the screen size? Like somewhere in the code where you get the screen size from tty?

**Comment by cylgom** [comment]
fixed in upcoming version

**Comment by Mati24** [comment]
Hello,
How can we change the screen size ? I have a 13" with 3840x2180. In wayland, I set the scale by 2

**Comment by oxodao** [comment]
I'm worried that there is nothing much to do. According to the [Arch wiki](https://wiki.archlinux.org/index.php/HiDPI#Linux_console) the console can only change it's font size to make thing bigger...

**Comment by Mati24** [comment]
Too bad, thank you :)
