### ISSUE TITLE
Decouple from systemd?

### ISSUE THREAD

**Issue by Anachron** [cylgom/ly#44]
I am using a distro where systemd is purposefully stripped of. Is it hard to remove the systemd dependency?

**Comment by cylgom** [comment]
systemd has nothing to do with the software in itself. However I only provide a systemd service file, so you will have to figure out how to install one with your init. Feel free to open a PR to add support for your init once it's done!

**Comment by Anachron** [comment]
Void uses runit,- I'll see what I can do. Happy to know the code itself does not depend on systemd. 

Thanks!
