### ISSUE TITLE
linux-pam block root login?

### ISSUE THREAD

**Issue by dmknght** [cylgom/ly#46]
Hi! I am creating a custom amd64 kali ISO with fluxbox and ly. After installation, i had this error:
`Pam Transaction Aborted`.
After reading all issues, i changed lib path link from `/usr/lib/security/pam_loginuid.so` to `/usr/lib/x86_64-linux-gnu/security/pam_loginuid`. Howerver, This issue still showed.
After creating an account (`test:test`), I found out i can login as non-root user.
Am I missing something? I cloned and did every step in README.md file. I also searched "linux pam login user" but there is no useful thing.

**Comment by cylgom** [comment]
If you're still out there, watch this repo as a major update is coming. It should fix this issue.

**Comment by cylgom** [comment]
Ok, so this still happens. I have no idea why, and will try to investigate

**Comment by dmknght** [comment]
Hi! I am thinking this bug is similar root login error via SSH. There must be something inside PAM allowing /denying login as root. Sadly can't test and debug it now. I'll give new information here if I have new result.

**Comment by cylgom** [comment]
Ok, so I think this is how PAM is supposed to work. I'm closing for now.
