### ISSUE TITLE
Ly exit with error code 0 when pressing 'Fn'

### ISSUE THREAD

**Issue by Fnux** [cylgom/ly#47]
Hello,

When I press the 'Fn' key  (151 XF86WakeUp for my X server) on my Thinkpad T440s, ly simply exit with error code 0. I don't think that's a good thing for a DM ;-)

**Comment by qub1750ul** [comment]
Are you building ly using the lastest commit ?

**Comment by Fnux** [comment]
I'm using the latest (and only) release: v0.0.1. Was this bug fixed in the meantime ?

**Comment by qub1750ul** [comment]
I've personally submitted a fix for a similar problem ( #45 ), and it has been merged only after the release v0.0.1 .
I suggest to try building ly from the very latest commit, and see if it solves the problem.

**Comment by Fnux** [comment]
Yep, that's it. Thank you!
