### ISSUE TITLE
desktop environment

### ISSUE THREAD

**Issue by swatalla** [cylgom/ly#5]
How do we set the desktop environment? I have tried messing with several settings but Ly is neither autodetecting nor responding to any changes I make to the config/lang/etc files to adjust the wm. I am using i3 for my wm.

edit: just wanted to add that I think this is the most beautifully minimalist login manager i have ever seen

**Comment by oxodao** [comment]
i3 is auto-detected. That's how it works for me at least.
If it does not work you can still put it in your ~/.xinitrc and choose the option "xinitrc" in the DE selection in ly

**Comment by swatalla** [comment]
so I have echoed exec i3 to my .xinitrc, but ly is still sending me straight to the shell. any more hints?

**Comment by cylgom** [comment]
Did you set the target desktop before logging in? If not, go to the first field (above the username) with the up / down arrow keys, and select your desktop with the left / right arrow keys. Your choice is saved automatically when you log in and becomes the new default. If i3 does not appear in the list, create the corresponding desktop file ("/usr/share/xsessions/i3.desktop"):

[Desktop Entry]
Name=i3
Comment=improved dynamic tiling window manager
Exec=i3
TryExec=i3
Type=Application
X-LightDM-DesktopName=i3
DesktopNames=i3
Keywords=tiling;wm;windowmanager;window;manager;

Hope it helps ;)

**Comment by swatalla** [comment]
Haha! I never would have guessed to use the left and right arrows to scroll in the field above username. That did it! Thanks!!
