### ISSUE TITLE
Undefined reference to *

### ISSUE THREAD

**Issue by ohunter** [cylgom/ly#53]
compiling build/ly
obj/login.o: In function `start_env':
/home/oj/Downloads/Gits/ly/src/login.c:112: undefined reference to `pam_start'
/home/oj/Downloads/Gits/ly/src/login.c:132: undefined reference to `pam_end'
/home/oj/Downloads/Gits/ly/src/login.c:137: undefined reference to `pam_authenticate'
/home/oj/Downloads/Gits/ly/src/login.c:169: undefined reference to `pam_end'
/home/oj/Downloads/Gits/ly/src/login.c:174: undefined reference to `pam_acct_mgmt'
/home/oj/Downloads/Gits/ly/src/login.c:205: undefined reference to `pam_end'
/home/oj/Downloads/Gits/ly/src/login.c:216: undefined reference to `pam_end'
/home/oj/Downloads/Gits/ly/src/login.c:225: undefined reference to `pam_end'
/home/oj/Downloads/Gits/ly/src/login.c:230: undefined reference to `pam_setcred'
/home/oj/Downloads/Gits/ly/src/login.c:265: undefined reference to `pam_end'
/home/oj/Downloads/Gits/ly/src/login.c:270: undefined reference to `pam_open_session'
/home/oj/Downloads/Gits/ly/src/login.c:274: undefined reference to `pam_setcred'
/home/oj/Downloads/Gits/ly/src/login.c:307: undefined reference to `pam_end'
/home/oj/Downloads/Gits/ly/src/login.c:318: undefined reference to `def_prog_mode'
/home/oj/Downloads/Gits/ly/src/login.c:319: undefined reference to `endwin'
/home/oj/Downloads/Gits/ly/src/login.c:330: undefined reference to `pam_end'
/home/oj/Downloads/Gits/ly/src/login.c:341: undefined reference to `pam_end'
/home/oj/Downloads/Gits/ly/src/login.c:349: undefined reference to `pam_end'
/home/oj/Downloads/Gits/ly/src/login.c:379: undefined reference to `pam_close_session'
/home/oj/Downloads/Gits/ly/src/login.c:399: undefined reference to `pam_end'
/home/oj/Downloads/Gits/ly/src/login.c:404: undefined reference to `pam_setcred'
/home/oj/Downloads/Gits/ly/src/login.c:439: undefined reference to `pam_end'
/home/oj/Downloads/Gits/ly/src/login.c:444: undefined reference to `pam_end'
/home/oj/Downloads/Gits/ly/src/login.c:449: undefined reference to `stdscr'
/home/oj/Downloads/Gits/ly/src/login.c:449: undefined reference to `wrefresh'
/home/oj/Downloads/Gits/ly/src/login.c:454: undefined reference to `stdscr'
/home/oj/Downloads/Gits/ly/src/login.c:454: undefined reference to `wrefresh'
obj/login.o: In function `init_env':
/home/oj/Downloads/Gits/ly/src/login.c:582: undefined reference to `pam_getenvlist'
obj/main.o: In function `main':
/home/oj/Downloads/Gits/ly/src/main.c:89: undefined reference to `form_driver'
/home/oj/Downloads/Gits/ly/src/main.c:91: undefined reference to `set_current_field'
/home/oj/Downloads/Gits/ly/src/main.c:92: undefined reference to `form_driver'
/home/oj/Downloads/Gits/ly/src/main.c:96: undefined reference to `current_field'
/home/oj/Downloads/Gits/ly/src/main.c:104: undefined reference to `form_driver'
/home/oj/Downloads/Gits/ly/src/main.c:111: undefined reference to `field_buffer'
/home/oj/Downloads/Gits/ly/src/main.c:112: undefined reference to `field_buffer'
/home/oj/Downloads/Gits/ly/src/main.c:127: undefined reference to `set_field_buffer'
/home/oj/Downloads/Gits/ly/src/main.c:148: undefined reference to `set_current_field'
/home/oj/Downloads/Gits/ly/src/main.c:154: undefined reference to `form_driver'
/home/oj/Downloads/Gits/ly/src/main.c:155: undefined reference to `form_driver'
/home/oj/Downloads/Gits/ly/src/main.c:160: undefined reference to `form_driver'
/home/oj/Downloads/Gits/ly/src/main.c:161: undefined reference to `form_driver'
/home/oj/Downloads/Gits/ly/src/main.c:168: undefined reference to `form_driver'
obj/main.o:/home/oj/Downloads/Gits/ly/src/main.c:172: more undefined references to `form_driver' follow
obj/main.o: In function `main':
/home/oj/Downloads/Gits/ly/src/main.c:202: undefined reference to `endwin'
/home/oj/Downloads/Gits/ly/src/main.c:209: undefined reference to `endwin'
/home/oj/Downloads/Gits/ly/src/main.c:215: undefined reference to `form_driver'
/home/oj/Downloads/Gits/ly/src/main.c:94: undefined reference to `wgetch'
/home/oj/Downloads/Gits/ly/src/main.c:224: undefined reference to `endwin'
obj/ncui.o: In function `init_ncurses':
/home/oj/Downloads/Gits/ly/src/ncui.c:32: undefined reference to `initscr'
/home/oj/Downloads/Gits/ly/src/ncui.c:33: undefined reference to `raw'
/home/oj/Downloads/Gits/ly/src/ncui.c:34: undefined reference to `noecho'
obj/ncui.o: In function `init_form':
/home/oj/Downloads/Gits/ly/src/ncui.c:72: undefined reference to `new_field'
/home/oj/Downloads/Gits/ly/src/ncui.c:76: undefined reference to `set_field_buffer'
/home/oj/Downloads/Gits/ly/src/ncui.c:77: undefined reference to `set_field_opts'
/home/oj/Downloads/Gits/ly/src/ncui.c:80: undefined reference to `new_field'
/home/oj/Downloads/Gits/ly/src/ncui.c:81: undefined reference to `TYPE_ENUM'
/home/oj/Downloads/Gits/ly/src/ncui.c:81: undefined reference to `set_field_type'
/home/oj/Downloads/Gits/ly/src/ncui.c:85: undefined reference to `set_field_buffer'
/home/oj/Downloads/Gits/ly/src/ncui.c:90: undefined reference to `set_field_buffer'
/home/oj/Downloads/Gits/ly/src/ncui.c:94: undefined reference to `set_field_opts'
/home/oj/Downloads/Gits/ly/src/ncui.c:98: undefined reference to `new_field'
/home/oj/Downloads/Gits/ly/src/ncui.c:99: undefined reference to `set_field_buffer'
/home/oj/Downloads/Gits/ly/src/ncui.c:100: undefined reference to `set_field_opts'
/home/oj/Downloads/Gits/ly/src/ncui.c:103: undefined reference to `new_field'
/home/oj/Downloads/Gits/ly/src/ncui.c:104: undefined reference to `set_field_buffer'
/home/oj/Downloads/Gits/ly/src/ncui.c:105: undefined reference to `set_field_opts'
/home/oj/Downloads/Gits/ly/src/ncui.c:108: undefined reference to `new_field'
/home/oj/Downloads/Gits/ly/src/ncui.c:112: undefined reference to `set_field_buffer'
/home/oj/Downloads/Gits/ly/src/ncui.c:115: undefined reference to `set_field_opts'
/home/oj/Downloads/Gits/ly/src/ncui.c:119: undefined reference to `new_field'
/home/oj/Downloads/Gits/ly/src/ncui.c:120: undefined reference to `set_field_buffer'
/home/oj/Downloads/Gits/ly/src/ncui.c:121: undefined reference to `set_field_opts'
/home/oj/Downloads/Gits/ly/src/ncui.c:124: undefined reference to `new_field'
/home/oj/Downloads/Gits/ly/src/ncui.c:125: undefined reference to `set_field_opts'
/home/oj/Downloads/Gits/ly/src/ncui.c:130: undefined reference to `new_form'
/home/oj/Downloads/Gits/ly/src/ncui.c:131: undefined reference to `form_opts_off'
/home/oj/Downloads/Gits/ly/src/ncui.c:132: undefined reference to `scale_form'
obj/ncui.o: In function `init_win':
/home/oj/Downloads/Gits/ly/src/ncui.c:140: undefined reference to `stdscr'
/home/oj/Downloads/Gits/ly/src/ncui.c:140: undefined reference to `stdscr'
/home/oj/Downloads/Gits/ly/src/ncui.c:140: undefined reference to `stdscr'
/home/oj/Downloads/Gits/ly/src/ncui.c:140: undefined reference to `stdscr'
/home/oj/Downloads/Gits/ly/src/ncui.c:148: undefined reference to `newwin'
/home/oj/Downloads/Gits/ly/src/ncui.c:150: undefined reference to `keypad'
obj/ncui.o: In function `init_scene':
/home/oj/Downloads/Gits/ly/src/ncui.c:155: undefined reference to `set_form_win'
/home/oj/Downloads/Gits/ly/src/ncui.c:156: undefined reference to `derwin'
/home/oj/Downloads/Gits/ly/src/ncui.c:156: undefined reference to `set_form_sub'
obj/ncui.o: In function `init_draw':
/home/oj/Downloads/Gits/ly/src/ncui.c:165: undefined reference to `wborder'
/home/oj/Downloads/Gits/ly/src/ncui.c:172: undefined reference to `mvprintw'
/home/oj/Downloads/Gits/ly/src/ncui.c:174: undefined reference to `stdscr'
/home/oj/Downloads/Gits/ly/src/ncui.c:174: undefined reference to `wrefresh'
/home/oj/Downloads/Gits/ly/src/ncui.c:176: undefined reference to `post_form'
/home/oj/Downloads/Gits/ly/src/ncui.c:178: undefined reference to `wrefresh'
obj/ncui.o: In function `end_form':
/home/oj/Downloads/Gits/ly/src/ncui.c:184: undefined reference to `unpost_form'
/home/oj/Downloads/Gits/ly/src/ncui.c:185: undefined reference to `free_form'
/home/oj/Downloads/Gits/ly/src/ncui.c:186: undefined reference to `free_field'
/home/oj/Downloads/Gits/ly/src/ncui.c:187: undefined reference to `free_field'
/home/oj/Downloads/Gits/ly/src/ncui.c:188: undefined reference to `free_field'
/home/oj/Downloads/Gits/ly/src/ncui.c:189: undefined reference to `free_field'
/home/oj/Downloads/Gits/ly/src/ncui.c:190: undefined reference to `free_field'
obj/ncui.o:/home/oj/Downloads/Gits/ly/src/ncui.c:191: more undefined references to `free_field' follow
obj/utils.o: In function `error_init':
/home/oj/Downloads/Gits/ly/src/utils.c:118: undefined reference to `mvwprintw'
/home/oj/Downloads/Gits/ly/src/utils.c:119: undefined reference to `mvwprintw'
obj/utils.o: In function `get_curses_char':
/home/oj/Downloads/Gits/ly/src/utils.c:130: undefined reference to `newscr'
/home/oj/Downloads/Gits/ly/src/utils.c:130: undefined reference to `wmove'
/home/oj/Downloads/Gits/ly/src/utils.c:130: undefined reference to `newscr'
/home/oj/Downloads/Gits/ly/src/utils.c:130: undefined reference to `winch'
obj/utils.o: In function `cascade':
/home/oj/Downloads/Gits/ly/src/utils.c:149: undefined reference to `stdscr'
/home/oj/Downloads/Gits/ly/src/utils.c:149: undefined reference to `stdscr'
/home/oj/Downloads/Gits/ly/src/utils.c:149: undefined reference to `stdscr'
/home/oj/Downloads/Gits/ly/src/utils.c:149: undefined reference to `stdscr'
/home/oj/Downloads/Gits/ly/src/utils.c:180: undefined reference to `stdscr'
/home/oj/Downloads/Gits/ly/src/utils.c:180: undefined reference to `wmove'
/home/oj/Downloads/Gits/ly/src/utils.c:180: undefined reference to `stdscr'
/home/oj/Downloads/Gits/ly/src/utils.c:180: undefined reference to `waddch'
/home/oj/Downloads/Gits/ly/src/utils.c:181: undefined reference to `stdscr'
/home/oj/Downloads/Gits/ly/src/utils.c:181: undefined reference to `wmove'
/home/oj/Downloads/Gits/ly/src/utils.c:181: undefined reference to `stdscr'
/home/oj/Downloads/Gits/ly/src/utils.c:181: undefined reference to `waddch'
/home/oj/Downloads/Gits/ly/src/utils.c:185: undefined reference to `stdscr'
/home/oj/Downloads/Gits/ly/src/utils.c:185: undefined reference to `wrefresh'
collect2: error: ld returned 1 exit status
makefile:45: recipe for target 'build/ly' failed
make: *** [build/ly] Error 1

Im assuming that they are due to faulty dependencies but I have no idea as to what causes it

**Comment by qub1750ul** [comment]
There is mentioned a lot of ncurses stuff

**Comment by ohunter** [comment]
Ok, seeing as I have ncurses installed shouldn't that not happen?

**Comment by qub1750ul** [comment]
try running ```sudo ldconfig``` and then building again

**Comment by cylgom** [comment]
upcoming version no longer needs ncurses
