### ISSUE TITLE
systemctl enable ly.service failed

### ISSUE THREAD

**Issue by zzzgit** [cylgom/ly#58]
```bash
[root@arch ly]# systemctl enable ly.service
Failed to enable unit: File /etc/systemd/system/display-manager.service already exists and is a symlink to /usr/lib/systemd/system/gdm.service.

```

**Comment by ivanhercaz** [comment]
I had this problem too. Although this issue is closed, I want to comment in the solution I applied: it was necessary to replace the symlink. The easier method is to run:

`systemctl enable ly.service -f`

This remove the current symlink and create the one to `ly.service`.
