### ISSUE TITLE
Cannot Upgrade Ly-git

### ISSUE THREAD

**Issue by micrus** [cylgom/ly#61]
Hi, every time I try to update Ly to the newest version I have this error.
```

 ==> Avvio di pkgver() in corso...
==> ERRORE: pkgver is not allowed to contain colons, forward slashes, hyphens or whitespace.
==> ERRORE: pkgver() ha generato una versione non valida: 0.2-2-g7557e0f
Error making: ly-git

```

Package: ly-git
OS: Arch Linux
Kernel: 4.18.9-arch1-1-ARCH

**Comment by cylgom** [comment]
Hi, can you try that again now? I updated the package earlier this morning to fix that :/

**Comment by micrus** [comment]
Thanks a lot, all works now!
