### ISSUE TITLE
XFCE not launching

### ISSUE THREAD

**Issue by anupam-git** [cylgom/ly#65]
I myself dont use a Display Manager. Love the CLI login and manually starting the xserver.
One day I was surfing GitHub and suddenly came to know about Ly. Looked cool and wanted to try.

As of now, I have Ly installed and Ly is launching at login. but my XFCE session is not starting after login.
Ly sits idly after successful login and nothing launches. I have move to another tty, then login and start the x server.

Any ideas on why it is not launching the xfce session?

PS : I don't know that much about xserver and it's configurations. It's very confusing.. :-P

**Comment by cylgom** [comment]
Hi, I just tried xfce4 on my fresh archlinux install and it seems to work, can you tell me which distro you are using? Is there any particular configuration on your system?

**Comment by anupam-git** [comment]
Fedora.. no specific configuration..
I launch using just `startx`

**Comment by RobertZenz** [comment]
> Ly sits idly after successful login and nothing launches.

Do you mean that the screen goes black and nothing happens, or that Ly stays visible? If Ly  stays visible, can you interact with it? Have you checked whether XFCE might have been started on a different TTY (Ctrl+Alt+F1-12)?

**Comment by anupam-git** [comment]
The compiling issue was a stupid one. It seems that the linked options (`$LINK` in your makefile) should be at given last.
Updated the makefile, and everything compiled good. 

Even ly is launching the session too.
All good now.

**Comment by cylgom** [comment]
Thanks a lot, I had no idea what could cause your issue. That's fixed in c13ca1c.

**Comment by anupam-git** [comment]
Now having another issue.

As of now, xfce launches in Ubuntu. But every command needs to be run as sudo.

Even running `ls` as from user shell gave the error.

Any idea what's happening?

**Comment by cylgom** [comment]
Wow. I have no idea. Ly clearly downgrades the permissions and prints an error if it fails. Maybe you can check if your user is in the necessary groups ? `groups youusername`

**Comment by RobertZenz** [comment]
Can you open a terminal in the ly launched XFCE session and run:

 * `id`
 * `groups`
 * `echo $HOME`

That is, if the opening of the terminal already requires `sudo`, you don't need to test this because that doesn't help. If the terminal can be opened without `sudo`, then please run these commands and post the exact output here. Also try to run the `ls` command again and also post the whole output.

**Comment by cylgom** [comment]
This is because the default configuration does not include `/bin` in the `PATH` variable. I use ArchLinux, and in that distro `/bin` is a symlink to `/usr/bin`, so I just included `/usr/bin` in the `PATH` by default. You just have to edit the `PATH` to be loaded in `/etc/ly/config.ini`:
```
path=/sbin:/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/env
```

**Comment by anupam-git** [comment]
Then why does starting with `startx` includes bin in `PATH`?

From what I see in my `/etc/ly/config.ini`, path variable is not being set in `config.ini`. Hence it should not get overridden.

**Comment by cylgom** [comment]
Well... startx is a wrapper for xinit, and thus initializes everything on its own.
Ly was made under Archlinux, and sets the `PATH` to whatever is in labeled `path` in the config. If you no not set this variable (the default config obviously does not, and has the line commented), it falls back to hardcoded defaults, which do not include /bin. But I guess I could add `/bin` for better support. In the meantime, you can set the `PATH` in config.ini if you want the things to work...

**Comment by cylgom** [comment]
I added `/bin` and `/sbin` in the default `PATH` with 5e7437b
