### ISSUE TITLE
Ly doesnt appear

### ISSUE THREAD

**Issue by Jedipottsy** [cylgom/ly#7]
Hi,
I've installed ly from git, and enabled the systemd file, but no login manager appears.

systemctl status shows

```
ly.service - ly ncurses display manager
   Loaded: loaded (/usr/lib/systemd/system/ly.service; enabled; vendor preset: disabled)
   Active: inactive (dead) since Thu 2017-09-14 11:13:43 BST; 2min 23s ago
  Process: 841 ExecStart=/usr/bin/ly (code=killed, signal=HUP)
 Main PID: 841 (code=killed, signal=HUP)

Sep 14 11:13:43 helios systemd[1]: Started ly ncurses display manager.
```

checked tty2 (default) along with the other tty's.

**Comment by cylgom** [comment]
Hi, can you try disabling getty on tty2 ?
`sudo systemctl disable getty@tty2.service`
If it loads after Ly, getty may kill the service.

**Comment by Jedipottsy** [comment]
Hi,
Just tried disabing getty @tty2 and it still doesnt appear.
Thanks

**Comment by cylgom** [comment]
I think this issue and #8 are the same, can you check where the pam library is ?

**Comment by Jedipottsy** [comment]
Think the problem may have been with my system. Did a fresh reinstall and it now work great, although the default selected field is the password field

**Comment by aep** [comment]
> Think the problem may have been with my system. Did a fresh reinstall and it now works great!

any idea what it might have been? got the same issue with _any_ dm suddenly after updating systemd, not just ly
