### ISSUE TITLE
Musl libc Compilation issue

### ISSUE THREAD

**Issue by travankor** [cylgom/ly#75]
```
src/login.c: In function 'init_env':
src/login.c:125:44: error: '_PATH_MAILDIR' undeclared (first use in this function)
  len = snprintf(tmp, sizeof(tmp), "%s/%s", _PATH_MAILDIR, pw->pw_name);
                                            ^~~~~~~~~~~~~
src/login.c:125:44: note: each undeclared identifier is reported only once for each function it appears in
make: *** [makefile:33: obj/src/login.o] Error 1
```

Musl seems to have paths.h but does not actually use it (?).

https://www.openwall.com/lists/musl/2014/03/29/5

**Comment by liweitianux** [comment]
@cylgom, I think that we don't need to set the `MAIL` environment variable, for the following reasons:
* I don't find any specification about the `MAIL`.
* On my Linux system there is no `MAIL` set (LightDM + XFCE4).

**Comment by cylgom** [comment]
@travankor thank you for reporting that, and feel free to report any other issue you have with musl :)
