### ISSUE TITLE
Multiple Monitor Control

### ISSUE THREAD

**Issue by Zorpos** [cylgom/ly#76]
Hi there,

Would it be possible to add support for multiple monitors? I know it's a bit of a niche issue, but my 'main' monitor is actually a side monitor. I'm sure someone else will have an issue with this in the future as well.

**Comment by cylgom** [comment]
What do you mean exactly? Is the desktop environment you are using not detecting other monitors when launched with Ly? It should not prevent you from configuring your displays with xrandr: I personnally launch a script from `.xsession` to handle that.

**Comment by RobertZenz** [comment]
I think @Zorpos means that ly is being opened on the wrong monitor and should be on the other one.

**Comment by cylgom** [comment]
Oh. Then it's just a matter of changing the tty Ly is started on. Get that number, change it in `/etc/ly/config.ini`:
```
tty=YOURNUMBER
```
And in `/usr/lib/systemd/system/ly.service`:
```
After=getty@ttyYOURNUMBER.service
TTYPath=/dev/ttyYOURNUMBER
```

**Comment by Zorpos** [comment]
All tty run on the left-most screen of three monitors, so changing the tty won't resolve the issue unfortunately. 

My driver is using KMS so a frame buffer solution won't help either. I'd essentially have to recompile my kernel with console FB flags and I'd prefer not to do that if at all possible.

**Comment by cylgom** [comment]
I'm afraid the entire point of using Ly is to have it run directly in ttys and replace the `login` from linux-utils`. You must change your configuration to have some ttys started on other video outputs.

**Comment by Zorpos** [comment]
Yea, was afraid it might be out of the scope of the project. Regardless, appreciate the help.
