### ISSUE TITLE
[i3][Manjaro] Make ly run startx?

### ISSUE THREAD

**Issue by makrLL** [cylgom/ly#83]
Hello, noob here. Running i3 on Manjaro, after login with ly the color settings (for urxvt for example) are not loaded and X behaves weirdly. Everything works fine if I manually run startx from another tty after login, so can I make it run startix instead of xinitrc?

**Comment by cylgom** [comment]
Do you use the "xinitrc" traget in the DE list ? If so you can try to choose "i3" directly, otherwise try it (it should emulate startx)

**Comment by makrLL** [comment]
Problem happens when i choose i3, sorry for not specifying that. If I choose "xinitrc" instead it keeps looping the ly login prompt.

**Comment by CaglanT** [comment]
This may have to do with issue #90

**Comment by Recidiviste** [comment]
I have the same issue. I use dunst, and because i want to use ly, dunst is kinda broken. I used `systemctl --user import-environement DISPLAY` to make it work in my .xinitrc
But if i use i3 option, i can't import environement, and if i use xinitrc, i have a loop that don't stop until i kill ly :/

**Comment by cylgom** [comment]
Could you try with the new release ?

**Comment by Recidiviste** [comment]
I tried. I remove my current `ly` installation (from the AUR, `ly-git`), cloned the repo, compiled it. Now, it seems it launch the X server. But i3 don't come. At least, X shows and this isn't a loop. I tried to copy my xinitrc to the /root directory (who knows ?), nothing different.

**Comment by oarriaga** [comment]
> Problem happens when i choose i3, sorry for not specifying that. If I choose "xinitrc" instead it keeps looping the ly login prompt. Do you need me to post my .xinitrc file?

I have the same looping problem when I choose "Xinitrc". Login in with "I3" does not call my .xinitrc.  Right now I log in with "Shell" and call "startx" and this works. I installed it from AUR 2 days ago.

**Comment by oarriaga** [comment]
OK the "bug" for the xinitrc loop was fixed by making my .xinitrc executable
chmod +x .xinitrc

**Comment by Recidiviste** [comment]
Works for me !

**Comment by cylgom** [comment]
Same issue as #90, forgot to close
