### ISSUE TITLE
Ly doesn't draw on screen until a button is pressed

### ISSUE THREAD

**Issue by qub1750ul** [cylgom/ly#84]
I noticed this suddently out of nothing.

- Using ly-0.2.1-1 from AUR
- getty@tty2 is masked

After some investigation i realized that
- this happens only on boot
- affects a fresh install of the package

**Comment by qub1750ul** [comment]
It disappeared after a while, not sure why

**Comment by arkanine1000** [comment]
Same issue here. Not sure what caused it.

**Comment by qub1750ul** [comment]
I recently switched to runit as init system, Ly works perfectly with that.
So, i suspect that this is systemd fault, clearing the screen after Ly finished drawing on the tty.
