### ISSUE TITLE
Field password selected before the login

### ISSUE THREAD

**Issue by Tchakatak** [cylgom/ly#86]
Hello, 

By default Ly select the field Password.
Is it possible to make him select the field login first ?

ly version 0.2.1.r16.g10bd01a

**Comment by joanvyc** [comment]
https://github.com/cylgom/ly/blob/master/readme.md#controls

**Comment by cylgom** [comment]
Added in the new release (change `default_input` in `/etc/ly/config.ini`).
Thank you for the idea :)
