### ISSUE TITLE
Using shell from pwd->pw_shell is a bad idea

### ISSUE THREAD

**Issue by sealmove** [cylgom/ly#92]
When I set xonsh as my default shell, ly couldn't launch xorg because in file login.c, lines 230-240, in-line bash is used. In other words ly assumes the default shell (which it finds from pwd->pw_shell) is bash-compatible, which is wrong...

I suggest to scan $PATH for "good" shells and use one of them to launch xorg. If no "good" shell is found, this can be logged.

**Comment by sealmove** [comment]
Or a simpler solution is to just use /bin/sh always

**Comment by oxodao** [comment]
Alpine doesn't ship with /bin/bsh, only ash if I'm not mistaken

**Comment by cylgom** [comment]
I think this is fixed now, could you try the new release ?
