### ISSUE TITLE
Wayland support?

### ISSUE THREAD

**Issue by smyjpmu** [cylgom/ly#93]
Wayland is around the corner yet ly doesn't support is afaik. I know that Wayland is extremely easy to support although I am not able to do so. Perhaps someone else could.

I have made this issue in order for someone to add such support. I am also posting it on the behalf of many others I know. Thx.

**Comment by FaithLV** [comment]
Was also hoping for wayland support. Posting here to make it visible that atleast two people are interested in it.

**Comment by cylgom** [comment]
Fixed in 262237f
