### ISSUE TITLE
dwm not working

### ISSUE THREAD

**Issue by paperbenni** [cylgom/ly#94]
If I select dwm in the menu and type in my login data it logs me in (just shows the usual ubuntu login messages), then freezes for a while and puts me back into ly, this time it's completely unresponsive.
Mate starts fine using ly. 
The x session is the one from the ubuntu 18.04 repos

**Comment by hsakbo** [comment]
I got the same issue... Did you fix it?

**Comment by drozdowsky** [comment]
I have `exec dwm` in .xinitrc and it works just fine

**Comment by cylgom** [comment]
Hi, could you try with the new version ? It fixes a lot of issues.
