### ISSUE TITLE
suid-less x11 support

### ISSUE THREAD

**Issue by roosemberth** [cylgom/ly#98]
Hi, 

I'm trying to make a module for nixos. We currently support two ways of starting an Xserver:
- Ran by root (e.g. slim).
- Ran by the user and have it receive the DRM fd from the display manager, which negociates it with logind on behalf of the server. (e.g. sddm).

ly currently only supports invoking xinit as a user, which requires a suid Xorg binary. I coldn't get this to work, mostly because of all restrictions regarding suid execution (e.g. cannot specify a config file in the nix store).

Would it be possible for ly to support logind for session management[^1]?

[^1]: https://www.freedesktop.org/wiki/Software/systemd/writing-display-managers/

**Comment by cylgom** [comment]
Hi,

First thank you for your interest. I don't really want to use `logind` for session management (mainly because it comes from systemd), but I can suggest you to try the new release which removes xinit from the process (and acts like a real display manager). Let me know how it goes :)

**Comment by roosemberth** [comment]
Managed to get in working with some minor systemd-agnostic modifications \o/

See #134 #135 #136 #137 

It just works now ;)
