### ISSUE TITLE
Segmention fault

### ISSUE THREAD

**Issue by drozdowsky** [cylgom/ly#99]
On service start (runit) I get this dump:
[core.txt](https://github.com/cylgom/ly/files/3169514/core.txt)
@ This does not happen on manual start (sudo make run)
Thank you

Best regards

**Comment by drozdowsky** [comment]
This does not happen on manual start (sudo make run)

**Comment by qub1750ul** [comment]
I've managed to successfully run ly as a runit service by starting it as a getty client.
Otherwise it will crash immediatley.

**Comment by drozdowsky** [comment]
@qub1750ul how to do so?
does getty have some parameter to execute command? Is it safe? 
sorry for asking I am currently not on pc

**Comment by qub1750ul** [comment]
Here is my service directory: [ly-tty2.tar.gz](https://github.com/cylgom/ly/files/3217017/ly-tty2.tar.gz)
Take a look yourself

**Comment by drozdowsky** [comment]
Works!
Grazie mille :)
